services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud_rtmp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    restart: unless-stopped
    command: uvicorn uvicorn_app:app --host 0.0.0.0 --port 8000 --proxy-headers
    environment:
      - APP_NAME=CloudRTMP
      - SECRET_KEY=change-this-in-prod
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/cloud_rtmp
      - VIDEOS_DIR=/videos
      - CORS_ORIGINS=*
    volumes:
      - ./backend:/app
      - videos:/videos
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
  videos:


